/*

Given two strings s and t which consist of only lowercase letters.

        String t is generated by random shuffling string s and then add one more letter at a random position.

        Find the letter that was added in t.

        Example:

            Input:
            s = "abcd"
            t = "abcde"

            Output:
            e

            Explanation:
            'e' is the letter that was added.

*/

public class FindTheDifference {

    /*

        XOR ^

        s = "abcd"
        t = "abcde"

        (int) 'a' = 97 = 0b1100001   ...    (int) 'z' = 122 = 0b1111010

        'a' ^ 'a' = 0
        0b1100001 ^ 0b1100001 = 0b0000000


        'a' ^ 'z' = 27
        0b1100001 ^ 0b1111010 = 0b0011011


    */
    public char findTheDifference(String s, String t) {

        char c = t.charAt(t.length()-1);

        for(int i = 0; i < s.length(); i++){

            c ^= t.charAt(i);
            c ^= s.charAt(i);

        }

        return c;
    }


}
